# Generated by Django 4.2.30 on 2026-05-02 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('airports', models.JSONField(default=list, help_text='List of major airports')),
                ('best_time', models.TextField(help_text='Best time to visit description')),
                ('visa_process', models.TextField(help_text='Detailed visa process description')),
                ('days_recommendation', models.JSONField(default=dict, help_text='Duration vs description mapping')),
                ('tips', models.JSONField(default=list, help_text='Pro-tips and things to keep in mind')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='itinerary',
            name='highlights',
            field=models.TextField(blank=True, help_text="Short highlight e.g. 'Kuala Lumpur + Langkawi'"),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='regular_price',
            field=models.DecimalField(decimal_places=2, default=999.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=799.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='destination_rel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='api.destination'),
        ),
    ]
