# Generated by Django 4.2.30 on 2026-05-02 19:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_destination_itinerary_highlights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.destination_image_path),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.itinerary_image_path),
        ),
    ]
