# Generated by Django 4.2.30 on 2026-05-03 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_itineraries', to=settings.AUTH_USER_MODEL),
        ),
    ]
