# Generated by Django 4.2.30 on 2026-05-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_itinerary_is_custom_itinerary_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
