# Generated by Django 4.2.30 on 2026-05-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_itinerary_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraryday',
            name='image',
        ),
        migrations.AlterField(
            model_name='destination',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
