# Generated by Django 4.2.30 on 2026-05-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_itineraryday_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryday',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='day_images/'),
        ),
    ]
