# Generated by Django 4.2.30 on 2026-05-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_itineraryday_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['-created_at']},
        ),
    ]
