# Generated by Django 4.2.30 on 2026-05-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_destination_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itineraryday',
            unique_together=set(),
        ),
    ]
