# Generated by Django 4.2.30 on 2026-05-03 18:56

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_itineraryday_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryday',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.itinerary_day_image_path),
        ),
    ]
