# Generated by Django 4.2.30 on 2026-05-03 19:22

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_itineraryday_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.destination_image_path)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('airports', models.JSONField(default=list, help_text='List of major airports')),
                ('best_time', models.TextField(help_text='Best time to visit description')),
                ('visa_process', models.TextField(help_text='Detailed visa process description')),
                ('days_recommendation', models.JSONField(default=dict, help_text='Duration vs description mapping')),
                ('tips', models.JSONField(default=list, help_text='Pro-tips and things to keep in mind')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='itinerary',
            options={'verbose_name_plural': 'Itineraries'},
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='destination_rel',
        ),
        migrations.AddField(
            model_name='destination',
            name='culture',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='destinations',
            field=models.ManyToManyField(related_name='itineraries_included', to='api.destination'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='content',
            field=models.JSONField(help_text='Detailed day-wise itinerary with timings and transfers'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='destination',
            field=models.CharField(help_text='Legacy field or primary destination summary', max_length=255),
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.destination_image_path)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('suggested_duration', models.DurationField(blank=True, help_text='Time to spend at this attraction', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='api.destination')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='api.country'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='api.country'),
        ),
        migrations.AlterUniqueTogether(
            name='destination',
            unique_together={('country', 'slug')},
        ),
        migrations.RemoveField(
            model_name='destination',
            name='airports',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='best_time',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='days_recommendation',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='tips',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='visa_process',
        ),
    ]
