# Generated by Django 4.2.30 on 2026-05-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_country_alter_destination_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
