# Generated by Django 4.2.30 on 2026-05-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_country_flag_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_itinerary_price', models.DecimalField(decimal_places=2, default=99.0, max_digits=10)),
                ('custom_itinerary_regular_price', models.DecimalField(decimal_places=2, default=199.0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
