# Generated by Django 4.2.30 on 2026-05-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='visa_info',
            field=models.JSONField(blank=True, help_text='Real-time visa requirements and special cases', null=True),
        ),
    ]
