# Generated by Django 4.2.30 on 2026-05-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_itinerary_visa_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='closing_days',
            field=models.CharField(blank=True, help_text='Days when this attraction is closed', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='ticket_price',
            field=models.CharField(blank=True, help_text='Latest ticket price or fee info', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='closing_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='opening_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='suggested_duration',
            field=models.CharField(blank=True, help_text='Time to spend at this attraction', max_length=100, null=True),
        ),
    ]
