# Generated by Django 4.2.30 on 2026-05-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_attraction_closing_days_attraction_ticket_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='visa_info',
        ),
    ]
