# Generated by Django 4.2.30 on 2026-05-04 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_itinerary_visa_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisaRule',
        ),
    ]
