# Generated by Django 4.2.30 on 2026-05-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_delete_visarule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='airports',
            field=models.JSONField(blank=True, default=list, help_text='List of major airports', null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='best_time',
            field=models.TextField(blank=True, help_text='Best time to visit description', null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='days_recommendation',
            field=models.JSONField(blank=True, default=dict, help_text='Duration vs description mapping', null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='tips',
            field=models.JSONField(blank=True, default=list, help_text='Pro-tips and things to keep in mind', null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='visa_process',
            field=models.TextField(blank=True, help_text='Detailed visa process description', null=True),
        ),
    ]
