# Generated by Django 4.2.30 on 2026-05-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_country_airports_alter_country_best_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='visa_requirements',
            field=models.TextField(blank=True, help_text='End-to-end visa process tailored for the specific traveler nationality.'),
        ),
    ]
