# Generated by Django 4.2.30 on 2026-05-05 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_userprofile_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nationality_itineraries', to='api.country'),
        ),
    ]
