# Generated by Django 4.2.30 on 2026-05-05 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_itinerary_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='visa_requirements',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='budget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='travel_style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_itineraries', to='api.country'),
        ),
        migrations.CreateModel(
            name='VisaRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_visa_rules', to='api.country')),
                ('source_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_visa_rules', to='api.country')),
            ],
            options={
                'verbose_name': 'Visa Requirement',
                'verbose_name_plural': 'Visa Requirements',
                'unique_together': {('source_country', 'destination_country')},
            },
        ),
    ]
