apiVersion: apps/v1
kind: Deployment
metadata:
  name: trippzi-portal
  namespace: trippzi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trippzi-portal
  template:
    metadata:
      labels:
        app: trippzi-portal
    spec:
      containers:
      - name: portal
        image: trippzi-portal:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: trippzi-portal-service
  namespace: trippzi
spec:
  selector:
    app: trippzi-portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
