"use client"

import { useState, useEffect } from "react"
import { motion } from "framer-motion"
import { Save, RefreshCw, DollarSign } from "lucide-react"

interface SettingsFormProps {
  initialData: any
  onSave: (data: any) => Promise<void>
}

export const SettingsForm = ({ initialData, onSave }: SettingsFormProps) => {
  const [formData, setFormData] = useState({
    custom_itinerary_price: "99.00",
    custom_itinerary_regular_price: "199.00"
  })
  const [saving, setSaving] = useState(false)

  useEffect(() => {
    if (initialData) {
      setFormData({
        custom_itinerary_price: initialData.custom_itinerary_price?.toString() || "99.00",
        custom_itinerary_regular_price: initialData.custom_itinerary_regular_price?.toString() || "199.00"
      })
    }
  }, [initialData])

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setSaving(true)
    try {
      await onSave({
        custom_itinerary_price: parseFloat(formData.custom_itinerary_price),
        custom_itinerary_regular_price: parseFloat(formData.custom_itinerary_regular_price)
      })
      alert("Settings updated successfully!")
    } catch (err) {
      alert("Failed to update settings")
    } finally {
      setSaving(false)
    }
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="max-w-2xl bg-white dark:bg-zinc-900 rounded-[2.5rem] border border-zinc-200 dark:border-zinc-800 p-8 shadow-xl"
    >
      <form onSubmit={handleSubmit} className="space-y-8">
        <div className="space-y-6">
          <h2 className="text-2xl font-bold flex items-center gap-2">
            <DollarSign className="w-6 h-6 text-primary" />
            Custom Itinerary Pricing
          </h2>
          <p className="text-zinc-500 text-sm">
            Configure the default pricing for custom-generated itineraries.
            These values will be applied to all new itineraries generated by AI.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-2">
              <label className="text-sm font-bold text-zinc-500 uppercase tracking-wider">Sale Price (Rs.)</label>
              <input
                type="number"
                step="0.01"
                required
                className="w-full px-4 py-3 rounded-xl border dark:border-zinc-800 dark:bg-zinc-800 focus:ring-2 focus:ring-primary/80 outline-none transition-all"
                value={formData.custom_itinerary_price}
                onChange={e => setFormData({ ...formData, custom_itinerary_price: e.target.value })}
              />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-bold text-zinc-500 uppercase tracking-wider">Regular Price (Rs.)</label>
              <input
                type="number"
                step="0.01"
                required
                className="w-full px-4 py-3 rounded-xl border dark:border-zinc-800 dark:bg-zinc-800 focus:ring-2 focus:ring-primary/80 outline-none transition-all"
                value={formData.custom_itinerary_regular_price}
                onChange={e => setFormData({ ...formData, custom_itinerary_regular_price: e.target.value })}
              />
            </div>
          </div>
        </div>

        <div className="pt-6 border-t border-zinc-100 dark:border-zinc-800">
          <button
            type="submit"
            disabled={saving}
            className="w-full flex items-center justify-center gap-2 bg-primary text-white py-4 rounded-2xl font-bold hover:bg-primary/90 transition-all shadow-lg shadow-primary/80/20 active:scale-[0.98] disabled:opacity-50"
          >
            {saving ? (
              <RefreshCw className="w-5 h-5 animate-spin" />
            ) : (
              <Save className="w-5 h-5" />
            )}
            {saving ? "SAVING..." : "SAVE SETTINGS"}
          </button>
        </div>
      </form>
    </motion.div>
  )
}
