import type { Metadata, Viewport } from "next";
import { Baloo_2, Lora } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { GoogleAnalytics } from "@next/third-parties/google";
import { GoogleOAuthProvider } from '@react-oauth/google';

const baloo = Baloo_2({
  variable: "--font-baloo",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trippzi | Smart Travel Itineraries",
  description: "Curated and personalized travel itineraries generated by AI, based on your passport and preferences.",
  manifest: "/manifest.json",
};

export const viewport: Viewport = {
  themeColor: "#000000",
};

import Script from "next/script";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${baloo.variable} ${lora.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col transition-colors duration-300 font-sans">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {(() => {
            const clientId = typeof window !== 'undefined' && (window as any).ENV?.NEXT_PUBLIC_GOOGLE_CLIENT_ID 
              ? (window as any).ENV.NEXT_PUBLIC_GOOGLE_CLIENT_ID 
              : process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;
            
            if (clientId) {
              return (
                <GoogleOAuthProvider clientId={clientId}>
                  {children}
                </GoogleOAuthProvider>
              );
            }
            return children;
          })()}
        </ThemeProvider>
        {(() => {
          const gaId = typeof window !== 'undefined' && (window as any).ENV?.NEXT_PUBLIC_GA_ID 
            ? (window as any).ENV.NEXT_PUBLIC_GA_ID 
            : process.env.NEXT_PUBLIC_GA_ID;
          
          if (gaId) {
            return <GoogleAnalytics gaId={gaId} />;
          }
          return null;
        })()}
        <Script src="/env.js" strategy="beforeInteractive" />
        <Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}
